/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dankgorillas;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;

/**
 *
 * @author tollefsonj
 */
public class Game_Panel extends BasePanel implements java.awt.event.ActionListener{

    private int FPS = 30;//this is also the game speed
    GameController game;
    public javax.swing.Timer gameTimer = 
         new javax.swing.Timer(1000 / FPS, this);
    String name1;
    String name2;
    int games;
    float gravity;
    
    /**
     * Creates new form Game_Panel
     */
    public Game_Panel(SystemFrame par, String n1, String n2, int toWin, float grav) 
    {
        initComponents();
        parentFrame = par;
        name1 = n1;
        name2 = n2;
        games = toWin;
        gravity = grav;
    }
    
    @Override
    public void setup()
    {
        setLayout(null);
        this.setBackground(new Color(4, 2, 172));//4 3 172
        game = new GameController(this, games, gravity);
        game.gameSetup(panelWidth, panelHeight, FPS, name1, name2);
        gameTimer.start();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void actionPerformed(ActionEvent ae) {
        //input
        game.gameTick();
        //System.out.println("tick");
        repaint();
    }
    
    @Override
   public void paintComponent(Graphics g)
   {
       game.drawGame(g);
   }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
