/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dankgorillas;

import java.awt.Color;

/**
 *
 * @author tollefsonj
 */
public class GameOver_Panel extends BasePanel {

    
    InputRequest over;
    InputRequest score;
    InputRequest player1;
    InputRequest player2;
    InputRequest anyKey;
    String name1;
    String name2;
    int score1;
    int score2;
    String spaces = "                              ";
    /**
     * Creates new form GameOver_Panel
     */
    public GameOver_Panel(SystemFrame par, String n1, String n2, int s1, int s2) {
        initComponents();
        parentFrame = par;
        name1 = n1;
        name2 = n2;
        score1 = s1;
        score2 = s2;
    }
    
    @Override
    public void setup()
    {
       setBackground(Color.BLACK);
        over = new InputRequest("GAME OVER!",
            getGraphics(), 0, Color.LIGHT_GRAY, 15);
        over.useAsLabel();
        addInput(over, 260, 80);
        score = new InputRequest("Score:",
            getGraphics(), 0, Color.LIGHT_GRAY, 15);
        score.useAsLabel();
        addInput(score, 280, 110);
        String spacing = spaces.substring(name1.length() - 1, spaces.length() -1);
        player1 = new InputRequest(name1 + spacing + score1,
            getGraphics(), 0, Color.LIGHT_GRAY, 15);
        player1.useAsLabel();
        addInput(player1, 240, 140);
        spacing = spaces.substring(name2.length() - 1, spaces.length() -1);
        player2 = new InputRequest(name2 + spacing + score2,
            getGraphics(), 0, Color.LIGHT_GRAY, 15);
        player2.useAsLabel();
        addInput(player2, 240, 170);
        anyKey = new InputRequest("Press any key to continue",
            getGraphics(), 0, Color.LIGHT_GRAY, 15);
        anyKey.lockValue();
        addInput(anyKey, 220, 310);
        
        anyKey.input.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) 
            {
                MainMenu mm = new MainMenu(parentFrame);
                parentFrame.switchPanel(mm);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
