/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dankgorillas;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;

/**
 *
 * @author tollefsonj
 */
public class Intro_Panel extends BasePanel  implements java.awt.event.ActionListener{

    private int FPS = 30;
    private int MAX_TIME = FPS * 5;
    private javax.swing.Timer gameTimer = 
         new javax.swing.Timer(1000 / FPS, this);
    int time = 0;
    String name1;
    String name2;
    int games;
    float gravity;
    Gorilla gor1;
    Gorilla gor2;
    
    /**
     * Creates new form Intro_Panel
     * @param n1
     * @param n2
     * @param toWin
     * @param grav
     */
    public Intro_Panel(SystemFrame par, String n1, String n2, int toWin, float grav) {
        initComponents();
        parentFrame = par;
        name1 = n1;
        name2 = n2;
        games = toWin;
        gravity = grav;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void actionPerformed(ActionEvent ae) {
        time ++;
        if(time >= MAX_TIME)
        {
            gameTimer.stop();
            Game_Panel gamePanel = new Game_Panel(parentFrame, name1, name2, games, gravity);
            parentFrame.switchPanel(gamePanel);
        }
        repaint();
    }

    @Override
    public void setup()
    {
        InputRequest gameName = new InputRequest("D A N K   G O R I L L A S", getGraphics(), 0, Color.WHITE, 14);
        InputRequest starLabel = new InputRequest("STARRING:", getGraphics(), 0, Color.WHITE, 11);
        InputRequest playerNames = new InputRequest(name1 + " AND " + name2, getGraphics(), 0, Color.WHITE, 11);
        gor1 = new Gorilla(240, 250);
        gor2 = new Gorilla(320, 250);
        gor1.VictoryDance();
        gor2.VictoryDance();
        gameName.useAsLabel();
        starLabel.useAsLabel();
        playerNames.useAsLabel();
        addInput(gameName, 220, 10);
        addInput(starLabel, 270, 30);
        addInput(playerNames, 245, 100);
        this.setBackground(new Color(4, 2, 172));
        this.setVisible(true);
        gameTimer.start();
    }
    
    @Override
    public void paintComponent(Graphics g)
    {
        g.setColor(new Color(4, 2, 172));
        g.fillRect(0, 0, panelWidth, panelHeight);
        gor1.draw(g);
        gor2.draw(g);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
